[custom.all.time-calendar-clock]
type = "local"
path = "."
ipkg = "time-calendar-clock.ipkg"
test = "test/test.ipkg"

[custom.all.time-calendar-clock-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.missing-numeric]
type = "github"
url  = "https://github.com/seagull-kamome/idris2-missing-numeric.git"
commit = "master"
ipkg = "missing-numeric.ipkg"
