name: AnyCommit
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - $default-branch

env:
  SCHEME: scheme
  IDRIS2_CFLAGS: -O2

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CC: clang
      PACK_DIR: /root/.pack
    container: ghcr.io/stefan-hoeck/idris2-pack:latest    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Setup dependencies
        run: |
          apt-get update
          apt-get -y install gcc clang-14

      - name: Checkout
        uses: actions/checkout@v3

      - run: idris2 --version
      - run: pack install-deps time-calendar-clock
      - run: pack build time-calendar-clock
      - run: IDRIS2_CG=chez pack test time-calendar-clock
      - run: IDRIS2_CG=refc IDRIS2_CC=gcc pack test time-calendar-clock
      - run: IDRIS2_CG=refc IDRIS2_CC=clang-14 pack test time-calendar-clock
      - run: IDRIS2_CG=node pack test time-calendar-clock
      - run: pack install time-calendar-clock

